/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mcf_redfield.atq.view;

import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class JFrameMain extends javax.swing.JFrame
{

    /**
     * Creates new form JFrameMain
     */
    public JFrameMain()
    {
        this.setExtendedState(MAXIMIZED_BOTH);
        initComponents();
        jIFQCadastrar.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jIFQCadastrar = new javax.swing.JInternalFrame();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuQuestao = new javax.swing.JMenu();
        jMIQCadastrar = new javax.swing.JMenuItem();
        jMIQListar = new javax.swing.JMenuItem();
        jMenuCategoria = new javax.swing.JMenu();
        jMICCadastrar = new javax.swing.JMenuItem();
        jMICListar = new javax.swing.JMenuItem();
        jMenuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("PainelMain"));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jIFQCadastrar.setTitle("Cadastrar Questão");
        jIFQCadastrar.setVisible(true);

        jButton1.setText("jButton1");

        javax.swing.GroupLayout jIFQCadastrarLayout = new javax.swing.GroupLayout(jIFQCadastrar.getContentPane());
        jIFQCadastrar.getContentPane().setLayout(jIFQCadastrarLayout);
        jIFQCadastrarLayout.setHorizontalGroup(
            jIFQCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jIFQCadastrarLayout.createSequentialGroup()
                .addContainerGap(577, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jIFQCadastrarLayout.setVerticalGroup(
            jIFQCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jIFQCadastrarLayout.createSequentialGroup()
                .addContainerGap(221, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jIFQCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jIFQCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenuQuestao.setMnemonic('q');
        jMenuQuestao.setText("Questão");

        jMIQCadastrar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        jMIQCadastrar.setText("Cadastrar");
        jMIQCadastrar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMIQCadastrarActionPerformed(evt);
            }
        });
        jMenuQuestao.add(jMIQCadastrar);

        jMIQListar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_MASK));
        jMIQListar.setText("Listar");
        jMIQListar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMIQListarActionPerformed(evt);
            }
        });
        jMenuQuestao.add(jMIQListar);

        jMenuBar1.add(jMenuQuestao);

        jMenuCategoria.setMnemonic('c');
        jMenuCategoria.setText("Categoria");

        jMICCadastrar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        jMICCadastrar.setText("Cadastrar");
        jMICCadastrar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMICCadastrarActionPerformed(evt);
            }
        });
        jMenuCategoria.add(jMICCadastrar);

        jMICListar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_MASK));
        jMICListar.setText("Listar");
        jMICListar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMICListarActionPerformed(evt);
            }
        });
        jMenuCategoria.add(jMICListar);

        jMenuBar1.add(jMenuCategoria);

        jMenuSair.setText("Sair");
        jMenuBar1.add(jMenuSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMIQCadastrarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMIQCadastrarActionPerformed
    {//GEN-HEADEREND:event_jMIQCadastrarActionPerformed
        //JOptionPane.showMessageDialog(rootPane, "Questões >>> Cadastrar");
        jIFQCadastrar.setVisible(true);
    }//GEN-LAST:event_jMIQCadastrarActionPerformed

    private void jMIQListarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMIQListarActionPerformed
    {//GEN-HEADEREND:event_jMIQListarActionPerformed
        JOptionPane.showMessageDialog(rootPane, "Questões >>> Listar");
    }//GEN-LAST:event_jMIQListarActionPerformed

    private void jMICCadastrarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMICCadastrarActionPerformed
    {//GEN-HEADEREND:event_jMICCadastrarActionPerformed
        JOptionPane.showMessageDialog(rootPane, "Categorias >>> Cadastrar");
    }//GEN-LAST:event_jMICCadastrarActionPerformed

    private void jMICListarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMICListarActionPerformed
    {//GEN-HEADEREND:event_jMICListarActionPerformed
        JOptionPane.showMessageDialog(rootPane, "Categorias >>> Listar");
    }//GEN-LAST:event_jMICListarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new JFrameMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JInternalFrame jIFQCadastrar;
    private javax.swing.JMenuItem jMICCadastrar;
    private javax.swing.JMenuItem jMICListar;
    private javax.swing.JMenuItem jMIQCadastrar;
    private javax.swing.JMenuItem jMIQListar;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCategoria;
    private javax.swing.JMenu jMenuQuestao;
    private javax.swing.JMenu jMenuSair;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
